# automatically generated by the FlatBuffers compiler, do not modify

# namespace: shardfile

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Example(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Example()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExample(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Example
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Example
    def Attributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sedpack.io.flatbuffer.shardfile.Attribute import Attribute
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Example
    def AttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Example
    def AttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ExampleStart(builder):
    builder.StartObject(1)

def Start(builder):
    ExampleStart(builder)

def ExampleAddAttributes(builder, attributes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(attributes), 0)

def AddAttributes(builder, attributes):
    ExampleAddAttributes(builder, attributes)

def ExampleStartAttributesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttributesVector(builder, numElems):
    return ExampleStartAttributesVector(builder, numElems)

def ExampleEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExampleEnd(builder)
