# automatically generated by the FlatBuffers compiler, do not modify

# namespace: shardfile

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Shard(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shard()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShard(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Shard
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shard
    def Examples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sedpack.io.flatbuffer.shardfile.Example import Example
            obj = Example()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shard
    def ExamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shard
    def ExamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ShardStart(builder):
    builder.StartObject(1)

def Start(builder):
    ShardStart(builder)

def ShardAddExamples(builder, examples):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(examples), 0)

def AddExamples(builder, examples):
    ShardAddExamples(builder, examples)

def ShardStartExamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExamplesVector(builder, numElems):
    return ShardStartExamplesVector(builder, numElems)

def ShardEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShardEnd(builder)
