name: piptest
on:
  push:
    paths:
      - 'docs/**/*.py'
      - 'pytest.ini'
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: 0 5 * * 1 # Every Monday at 5:00 UTC

jobs:
  piptesting:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: x86
          - runner: ubuntu-latest
            target: aarch64
          - runner: ubuntu-latest
            target: armv7
          - runner: ubuntu-latest
            target: s390x
          - runner: ubuntu-latest
            target: ppc64le
          - runner: windows-latest
            target: x64
          - runner: windows-latest
            target: x86
          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing sedpack pip package
        run: |
          pip install sedpack
      - name: Run tutorial using sedpack pip package
        run: |
          python docs/tutorials/quick_start/mnist_save.py -d mnist_dataset
          python docs/tutorials/quick_start/mnist_read.py -d mnist_dataset
