name: piptest
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**/*.py'
      - 'pytest.ini'
  schedule:
    - cron: 0 5 * * 1 # Every Monday at 5:00 UTC

jobs:
  piptesting:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        # ubuntu-24.04-arm is not stable enough
        platform:
          - runner: ubuntu-latest  # x64
          - runner: windows-latest  # x64
          - runner: macos-14  # arm64
          - runner: macos-15-intel  # Intel
          - runner: macos-latest  # arm64
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing sedpack pip package
        run: |
          pip install sedpack
      - name: Run tutorial using sedpack pip package
        run: |
          python docs/tutorials/quick_start/mnist_save.py -d mnist_dataset
          python docs/tutorials/quick_start/mnist_read_keras.py -d mnist_dataset
