name: yapf
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.py'
  merge_group:  # Needed for required workflows
  # Run after a review has been submitted (this is a required workflow which
  # might not be triggered when no code changes -- trigger before going to
  # merge queue).
  pull_request_review:
    types: [submitted]

jobs:
  yapf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade 'yapf>=0.30.0'
      - name: Register matcher
        run:
          echo ::add-matcher::./.github/python_matcher.json
      - name: Test code formatting with yapf
        run:
          yapf --recursive --diff .
